service: hello-aws
	
useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  deploymentMethod: direct
  region: us-east-1
  iam:
    role: arn:aws:iam::673479169827:role/CCThomasHelloAWS

custom:
  serverless-offline:
    httpPort: 4002
    lambdaPort: 4003
    host: '127.0.0.1'

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - 'node_modules/pino/**'


functions:
  helloWorld:
    handler: dist/handlers/HelloWorld.handler
    package:
      - 'dist/handlers/HelloWorld.js'
    environment:
      LOG_LEVEL: 'debug'
    events:
      - http:
          path: helloworld
          method: get
