service: hello-aws
	
useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

custom:
  serverless-offline:
    httpPort: 4002
    lambdaPort: 4003
    host: '127.0.0.1'

package:
  individually: true

functions:
  helloWorld:
    handler: dist/handlers/HelloWorld.handler
    environment:
      LOG_LEVEL: 'debug'
    events:
      - http:
          path: helloworld
          method: get
