name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-unit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'


    - run: npm ci
    - run: npm run build
    - run: npm run test:unit

  test-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - run: npm ci
    - run: npm run build

    - name: Start application
      run: npm start &

    - name: Wait for application to start
      run: sleep 30 # Adjust this delay according to your application's startup time

    - name: Run integration tests
      run: npm run test:integration
